// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwxarljrnpxbewmqshyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3eGFybGpybnB4YmV3bXFzaHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTY3ODYsImV4cCI6MjA2MzUzMjc4Nn0.EHyeAgRRJrnFD-MTrrG4SeYOI4gLJl6nZgAfaMrYshs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);